import pybullet as p
import pybullet_data
import numpy as np
import math
import pandas as pd
import time
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# 0. PLAYBACK SETTINGS
# ============================================================
# Every row in the CSV is replayed, sorted by score. Mode of each row
# is read from its `mode` column and dispatched automatically.
CSV_PATH = "gait_results.csv"
TOP_N    = None   # None = replay all rows, or set an int (e.g. 5) for top-N only

# ============================================================
# 1. SETTINGS & GLOBALS (match the optimizer)
# ============================================================
PHYSICS_FREQ = 240
SERVO_FREQ   = 100
DURATION     = 10

L1 = 0.10
L2 = 0.10
URDF_X_OFFSET = 0.005
BODY_OFFSET   = 0.0544

GLOBAL_MAX_TORQUE   = 1.8
GLOBAL_MAX_VELOCITY = 6.0
LATERAL_FRICTION    = 1.0

# Diagonal-only
FORWARD_SHARE = 0.625

GAIT_LIBRARY = {"tripod": [0.0, 0.5, 0.0, 0.5, 0.0, 0.5]}
SPAWN_ORI = p.getQuaternionFromEuler([0, 0, 0])

LEG_ROOTS = {
    "FL": [0.12, 0.10], "ML": [0.0, 0.14], "RL": [-0.12, 0.10],
    "FR": [0.12, -0.10], "MR": [0.0, -0.14], "RR": [-0.12, -0.10],
}
LEG_PREFIXES = ["FL", "ML", "RL", "FR", "MR", "RR"]

servo_interval = int(PHYSICS_FREQ / SERVO_FREQ)

# ============================================================
# 2. IK
# ============================================================

def solve_leg_ik_3dof(target_x, target_y, target_z, current_body_height):
    x = target_x + URDF_X_OFFSET
    y = target_y
    z_from_thigh = -(target_z - BODY_OFFSET)
    hip_angle = math.atan2(y, -z_from_thigh)
    z_sagittal = -math.sqrt(y**2 + z_from_thigh**2)

    dist_sq = x**2 + z_sagittal**2
    dist = math.sqrt(dist_sq)

    if dist > (L1 + L2) * 0.99 or dist < abs(L1 - L2):
        return None, None, None

    cos_phi = (L1**2 + L2**2 - dist_sq) / (2 * L1 * L2)
    phi = math.acos(np.clip(cos_phi, -1.0, 1.0))
    knee_angle = math.pi - phi

    alpha = math.atan2(z_sagittal, x)
    cos_beta = (L1**2 + dist_sq - L2**2) / (2 * L1 * dist)
    beta = math.acos(np.clip(cos_beta, -1.0, 1.0))
    thigh_angle = alpha - beta + (math.pi / 2)

    return hip_angle, thigh_angle, knee_angle

# ============================================================
# 3. TRAJECTORY / PHASE DISPATCH (matches optimizer)
# ============================================================

def foot_target(mode, prefix, phase_multiplier, tz, dna, direction):
    if mode == "straight":
        return direction * dna["step_amplitude"] * phase_multiplier, 0.0, tz

    if mode == "sideway":
        return 0.0, direction * dna["step_amplitude"] * phase_multiplier, tz

    if mode == "diagonal":
        rad = math.radians(direction)  # direction is degrees here
        amp_x = dna["step_amplitude"] * FORWARD_SHARE
        amp_y = dna["step_amplitude"] * (1.0 - FORWARD_SHARE)
        sign_x = np.sign(math.cos(rad))
        sign_y = np.sign(math.sin(rad))
        tx = amp_x * phase_multiplier * abs(math.cos(rad)) * sign_x
        ty = amp_y * phase_multiplier * abs(math.sin(rad)) * sign_y
        return tx, ty, tz

    if mode == "spin":
        rx, ry = LEG_ROOTS[prefix]
        angle = dna["step_amplitude"] * phase_multiplier
        return -ry * angle * direction, rx * angle * direction, tz

    raise ValueError(f"Unknown mode {mode}")


def leg_phase_offset(mode, l_idx, cycle_phase, gait_offsets):
    if mode == "spin":
        prefix = LEG_PREFIXES[l_idx]
        is_group_a = prefix in ["FL", "RR", "ML"]
        return cycle_phase if is_group_a else (cycle_phase + 0.5) % 1.0
    return (cycle_phase + gait_offsets[l_idx]) % 1.0

# ============================================================
# 4. LOAD RESULTS CSV & FILTER
# ============================================================

df = pd.read_csv(CSV_PATH)
if "mode" not in df.columns:
    raise ValueError(f"{CSV_PATH} has no 'mode' column — was it generated by the unified optimizer?")

df = df.sort_values("score", ascending=False).reset_index(drop=True)
if TOP_N is not None:
    df = df.head(TOP_N)

if df.empty:
    raise SystemExit(f"{CSV_PATH} is empty.")

modes_present = sorted(df["mode"].unique().tolist())
print(f"Loaded {len(df)} trials from {CSV_PATH}  |  modes present: {modes_present}")

# ============================================================
# 5. INIT PYBULLET
# ============================================================

client_id = p.connect(p.GUI)
p.resetSimulation(physicsClientId=client_id)
p.setTimeStep(1.0 / PHYSICS_FREQ, physicsClientId=client_id)
p.setAdditionalSearchPath(pybullet_data.getDataPath(), physicsClientId=client_id)
p.setGravity(0, 0, -9.81, physicsClientId=client_id)
p.setRealTimeSimulation(0, physicsClientId=client_id)

plane_id = p.loadURDF("plane.urdf", physicsClientId=client_id)
p.changeDynamics(plane_id, -1, lateralFriction=LATERAL_FRICTION, physicsClientId=client_id)

# ============================================================
# 6. SPAWN ROBOT
# ============================================================

initial_height = float(df.iloc[0]["target_height"])

urdf_path = os.path.join(HERE, "HexaDog_ZBD.urdf")
robot = p.loadURDF(
    urdf_path, [0, 0, 0.05], SPAWN_ORI,
    physicsClientId=client_id,
    flags=p.URDF_USE_INERTIA_FROM_FILE | p.URDF_ENABLE_CACHED_GRAPHICS_SHAPES,
)

p.changeDynamics(robot, -1, lateralFriction=LATERAL_FRICTION, physicsClientId=client_id)
for j in range(p.getNumJoints(robot, physicsClientId=client_id)):
    p.changeDynamics(robot, j, lateralFriction=LATERAL_FRICTION, physicsClientId=client_id)

joint_map = {
    p.getJointInfo(robot, j, physicsClientId=client_id)[1].decode(): j
    for j in range(p.getNumJoints(robot, physicsClientId=client_id))
}

# ============================================================
# 7. SETTLE ROBOT
# ============================================================

def settle(body_height, seconds=2.0):
    h_set, th_set, kn_set = solve_leg_ik_3dof(0, 0, body_height, body_height)
    if h_set is None:
        return
    for _ in range(int(seconds * PHYSICS_FREQ)):
        for prefix in LEG_PREFIXES:
            is_left  = prefix.endswith("L")
            is_right = prefix.endswith("R")
            actual_th = -th_set if is_left else th_set
            actual_kn = -kn_set if is_left else kn_set
            if is_right:
                actual_th = th_set
            p.setJointMotorControl2(robot, joint_map[f"{prefix}3"], p.POSITION_CONTROL, h_set,   force=GLOBAL_MAX_TORQUE)
            p.setJointMotorControl2(robot, joint_map[f"{prefix}2"], p.POSITION_CONTROL, actual_th, force=GLOBAL_MAX_TORQUE)
            p.setJointMotorControl2(robot, joint_map[f"{prefix}1"], p.POSITION_CONTROL, actual_kn, force=GLOBAL_MAX_TORQUE)
        p.stepSimulation(physicsClientId=client_id)
        time.sleep(1.0 / PHYSICS_FREQ)

print("Settling robot...")
settle(initial_height, seconds=2.0)

# ============================================================
# 8. PLAYBACK LOOP
# ============================================================

for idx, row in df.iterrows():
    mode         = row["mode"]
    body_height  = float(row["target_height"])
    step_height  = float(row["step_height"])
    direction    = float(row["direction"])   # angle (deg) for diagonal, ±1 otherwise
    gait_offsets = GAIT_LIBRARY[row["gait"]]

    dna = {
        "step_amplitude": float(row["step_amplitude"]),
        "frequency":      float(row["frequency"]),
    }

    print("\n" + "=" * 60)
    print(f"Trial {idx+1}/{len(df)}  |  mode={mode}  |  score={row['score']:.4f}")
    print(f"dir={direction}  height={body_height}  step_h={step_height}  "
          f"amp={dna['step_amplitude']:.4f}  freq={dna['frequency']:.4f}")
    print("=" * 60)

    # --- Reset ---
    p.resetBasePositionAndOrientation(robot, [0, 0, body_height], SPAWN_ORI, physicsClientId=client_id)
    p.resetBaseVelocity(robot, [0, 0, 0], [0, 0, 0], physicsClientId=client_id)

    start_pos, start_orn = p.getBasePositionAndOrientation(robot, physicsClientId=client_id)
    start_xy = np.array(start_pos[:2])
    _, _, prev_yaw = p.getEulerFromQuaternion(start_orn)
    accumulated_yaw = 0.0

    # --- Run gait ---
    steps = int(DURATION * PHYSICS_FREQ)
    for s in range(steps):
        t = s / PHYSICS_FREQ

        if s % servo_interval == 0:
            cycle_phase = (t * dna["frequency"]) % 1.0

            for l_idx, prefix in enumerate(LEG_PREFIXES):
                phase = leg_phase_offset(mode, l_idx, cycle_phase, gait_offsets)
                s_phase = (phase if phase < 0.5 else phase - 0.5) * 2.0
                cycloid_factor = s_phase - (math.sin(2.0 * math.pi * s_phase) / (2.0 * math.pi))

                if phase < 0.5:  # Swing
                    phase_multiplier = (1.0 - 2.0 * cycloid_factor)
                    tz = body_height + step_height * 0.5 * (1.0 - math.cos(2.0 * math.pi * s_phase))
                else:            # Stance
                    phase_multiplier = (-1.0 + 2.0 * cycloid_factor)
                    tz = body_height

                tx, ty, tz = foot_target(mode, prefix, phase_multiplier, tz, dna, direction)

                h, th, kn = solve_leg_ik_3dof(tx, ty, tz, body_height)

                if h is not None:
                    is_left  = prefix.endswith("L")
                    is_right = prefix.endswith("R")
                    actual_th = -th if is_left else th
                    actual_kn = -kn if is_left else kn
                    if is_right:
                        actual_th = th

                    p.setJointMotorControl2(robot, joint_map[f"{prefix}3"], p.POSITION_CONTROL, h,         force=GLOBAL_MAX_TORQUE, maxVelocity=GLOBAL_MAX_VELOCITY)
                    p.setJointMotorControl2(robot, joint_map[f"{prefix}2"], p.POSITION_CONTROL, actual_th, force=GLOBAL_MAX_TORQUE, maxVelocity=GLOBAL_MAX_VELOCITY)
                    p.setJointMotorControl2(robot, joint_map[f"{prefix}1"], p.POSITION_CONTROL, actual_kn, force=GLOBAL_MAX_TORQUE, maxVelocity=GLOBAL_MAX_VELOCITY)

        p.stepSimulation(physicsClientId=client_id)
        time.sleep(1.0 / PHYSICS_FREQ)

        # Yaw accumulation (only used for spin readout)
        if mode == "spin":
            _, orn = p.getBasePositionAndOrientation(robot, physicsClientId=client_id)
            _, _, yaw = p.getEulerFromQuaternion(orn)
            diff = yaw - prev_yaw
            while diff > math.pi:  diff -= 2.0 * math.pi
            while diff < -math.pi: diff += 2.0 * math.pi
            accumulated_yaw += diff
            prev_yaw = yaw

    # --- Report (mode-specific) ---
    end_pos, _ = p.getBasePositionAndOrientation(robot, physicsClientId=client_id)
    end_xy = np.array(end_pos[:2])
    move_vec = end_xy - start_xy

    if mode == "straight":
        dist = move_vec[0] * direction
        print(f"Distance (forward):  {dist:.4f} m")
        print(f"Avg speed:           {dist / DURATION:.4f} m/s")
        print(f"Lateral drift:       {abs(move_vec[1]):.4f} m")

    elif mode == "sideway":
        dist = move_vec[1] * direction
        print(f"Distance (sideway):  {dist:.4f} m")
        print(f"Avg speed:           {dist / DURATION:.4f} m/s")
        print(f"Lateral drift:       {abs(move_vec[0]):.4f} m")

    elif mode == "diagonal":
        rad = math.radians(direction)
        heading = np.array([math.cos(rad), math.sin(rad)])
        dist = float(np.dot(move_vec, heading))
        lateral = float(np.linalg.norm(move_vec - dist * heading))
        print(f"Heading:             {direction:.1f} deg")
        print(f"Distance along dir:  {dist:.4f} m")
        print(f"Avg speed:           {dist / DURATION:.4f} m/s")
        print(f"Lateral drift:       {lateral:.4f} m")

    elif mode == "spin":
        rot_speed = accumulated_yaw / DURATION
        corrected = (accumulated_yaw * direction) / DURATION
        drift = float(np.linalg.norm(move_vec))
        print(f"Total rotation:      {accumulated_yaw:.4f} rad "
              f"({math.degrees(accumulated_yaw):.2f} deg)")
        print(f"Rot speed:           {rot_speed:.4f} rad/s "
              f"({math.degrees(rot_speed):.2f} deg/s)")
        print(f"Direction-corrected: {corrected:.4f} rad/s")
        print(f"XY drift:            {drift:.4f} m")

p.disconnect(client_id)
print("\nPlayback complete.")
